
package frc.robot.constants;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import java.util.Map;
import java.util.OptionalInt;

// If these imports cause errors because you're not using ChoreoLib,
// turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
import choreo.auto.AutoRoutine;
import choreo.auto.AutoTrajectory;

/**
 * A class containing the name, start pose, end pose, and total time of every Choreo trajectory.
 * This prevents your code from referencing deleted or misspelled trajectories,
 * and removes the need for JSON parsing to load a trajectory's essential data.
 * DO NOT MODIFY THIS FILE YOURSELF! It is automatically generated by Choreo.
 */
public record ChoreoTraj(
    String name,
    OptionalInt segment,
    double totalTimeSecs,
    Pose2d initialPoseBlue,
    Pose2d endPoseBlue
) {
    public static final ChoreoTraj Bump_Depot = new ChoreoTraj(
	    "Bump_Depot",
	    OptionalInt.empty(),
	    4.57843,
	    new Pose2d(3.592, 6.054, Rotation2d.fromRadians(0)),
	    new Pose2d(0.677, 5.994, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj Bump_HubLeft = new ChoreoTraj(
	    "Bump_HubLeft",
	    OptionalInt.empty(),
	    0.76282,
	    new Pose2d(3.6, 5.9, Rotation2d.fromRadians(-1.561)),
	    new Pose2d(2.6, 5.1, Rotation2d.fromRadians(-0.524))
	);
	public static final ChoreoTraj Climb = new ChoreoTraj(
	    "Climb",
	    OptionalInt.empty(),
	    3.0423,
	    new Pose2d(2.891, 4.205, Rotation2d.fromRadians(-1.571)),
	    new Pose2d(1.484, 4.205, Rotation2d.fromRadians(-1.571))
	);
	public static final ChoreoTraj Depot_Climb = new ChoreoTraj(
	    "Depot_Climb",
	    OptionalInt.empty(),
	    0.87656,
	    new Pose2d(2.458, 5.825, Rotation2d.fromRadians(0)),
	    new Pose2d(2.891, 4.205, Rotation2d.fromRadians(-1.571))
	);
	public static final ChoreoTraj Depot_HubFront = new ChoreoTraj(
	    "Depot_HubFront",
	    OptionalInt.empty(),
	    1.0895,
	    new Pose2d(0.677, 5.994, Rotation2d.fromRadians(0)),
	    new Pose2d(2.3, 4, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj Depot_Outpost = new ChoreoTraj(
	    "Depot_Outpost",
	    OptionalInt.empty(),
	    1.85023,
	    new Pose2d(2.458, 5.825, Rotation2d.fromRadians(0)),
	    new Pose2d(1.098, 0.648, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj HubFront_Outpost = new ChoreoTraj(
	    "HubFront_Outpost",
	    OptionalInt.empty(),
	    1.27208,
	    new Pose2d(2.3, 4, Rotation2d.fromRadians(0)),
	    new Pose2d(1.098, 0.648, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj HubLeft_Depot = new ChoreoTraj(
	    "HubLeft_Depot",
	    OptionalInt.empty(),
	    0.97205,
	    new Pose2d(2.6, 5.1, Rotation2d.fromRadians(-0.524)),
	    new Pose2d(0.677, 5.994, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj DepotTrench_Neutral = new ChoreoTraj(
	    "DepotTrench_Neutral",
	    OptionalInt.empty(),
	    4.88865,
	    new Pose2d(3.683, 7.568, Rotation2d.fromRadians(1.571)),
	    new Pose2d(7.601, 5.387, Rotation2d.fromRadians(1.588))
	);
	public static final ChoreoTraj Move_Forward_Depot = new ChoreoTraj(
	    "Move_Forward_Depot",
	    OptionalInt.empty(),
	    0.89109,
	    new Pose2d(0.677, 5.994, Rotation2d.fromRadians(0)),
	    new Pose2d(2.458, 5.825, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj Move_Forward_Outpost = new ChoreoTraj(
	    "Move_Forward_Outpost",
	    OptionalInt.empty(),
	    0.85958,
	    new Pose2d(1.098, 0.648, Rotation2d.fromRadians(0)),
	    new Pose2d(1.779, 2.156, Rotation2d.fromRadians(0.569))
	);
	public static final ChoreoTraj Neutral_HubLeft = new ChoreoTraj(
	    "Neutral_HubLeft",
	    OptionalInt.empty(),
	    1.62055,
	    new Pose2d(7.601, 5.387, Rotation2d.fromRadians(1.588)),
	    new Pose2d(2.956, 5.269, Rotation2d.fromRadians(-1.571))
	);
	public static final ChoreoTraj OppBump_OppHub = new ChoreoTraj(
	    "OppBump_OppHub",
	    OptionalInt.empty(),
	    0.67392,
	    new Pose2d(3.6, 2.6, Rotation2d.fromRadians(1.571)),
	    new Pose2d(2.7, 3, Rotation2d.fromRadians(0.524))
	);
	public static final ChoreoTraj OppNeutral_OppHub = new ChoreoTraj(
	    "OppNeutral_OppHub",
	    OptionalInt.empty(),
	    1.28791,
	    new Pose2d(7.604, 2.375, Rotation2d.fromRadians(-1.571)),
	    new Pose2d(2.779, 2.582, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj Op_Side_Neutral_Outpost = new ChoreoTraj(
	    "Op_Side_Neutral_Outpost",
	    OptionalInt.empty(),
	    4.69095,
	    new Pose2d(2.779, 2.582, Rotation2d.fromRadians(0)),
	    new Pose2d(0.677, 0.633, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj OutpostTrench_NeutralZone = new ChoreoTraj(
	    "OutpostTrench_NeutralZone",
	    OptionalInt.empty(),
	    4.26645,
	    new Pose2d(3.684, 0.499, Rotation2d.fromRadians(-1.571)),
	    new Pose2d(7.604, 2.375, Rotation2d.fromRadians(-1.571))
	);
	public static final ChoreoTraj Outpost_Tower = new ChoreoTraj(
	    "Outpost_Tower",
	    OptionalInt.empty(),
	    1.26169,
	    new Pose2d(0.6, 0.7, Rotation2d.fromRadians(0)),
	    new Pose2d(1.5, 3.5, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj O_Side_Climb = new ChoreoTraj(
	    "O_Side_Climb",
	    OptionalInt.empty(),
	    2.68316,
	    new Pose2d(2.854, 3.228, Rotation2d.fromRadians(-1.571)),
	    new Pose2d(1.564, 3.34, Rotation2d.fromRadians(-1.571))
	);
	public static final ChoreoTraj O_Side_Neutral_Climb = new ChoreoTraj(
	    "O_Side_Neutral_Climb",
	    OptionalInt.empty(),
	    0.86416,
	    new Pose2d(2.779, 2.582, Rotation2d.fromRadians(0)),
	    new Pose2d(2.891, 4.205, Rotation2d.fromRadians(-1.571))
	);
	public static final ChoreoTraj Reverse_From_Hub = new ChoreoTraj(
	    "Reverse_From_Hub",
	    OptionalInt.empty(),
	    0.84352,
	    new Pose2d(3.6, 4, Rotation2d.fromRadians(0)),
	    new Pose2d(2, 4, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj test = new ChoreoTraj(
	    "test",
	    OptionalInt.empty(),
	    1.18254,
	    new Pose2d(3.592, 6.054, Rotation2d.fromRadians(0)),
	    new Pose2d(3.592, 2.924, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj Trench_Outpost = new ChoreoTraj(
	    "Trench_Outpost",
	    OptionalInt.empty(),
	    3.00107,
	    new Pose2d(3.612, 0.412, Rotation2d.fromRadians(0)),
	    new Pose2d(0.733, 0.445, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj NewPath = new ChoreoTraj(
	    "NewPath",
	    OptionalInt.empty(),
	    1.93082,
	    new Pose2d(2.779, 2.582, Rotation2d.fromRadians(0)),
	    new Pose2d(7.604, 2.375, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj D_Side_Neutral_Climb = new ChoreoTraj(
	    "D_Side_Neutral_Climb",
	    OptionalInt.empty(),
	    0.68762,
	    new Pose2d(2.956, 5.269, Rotation2d.fromRadians(-1.571)),
	    new Pose2d(2.891, 4.205, Rotation2d.fromRadians(-1.571))
	);
	public static final ChoreoTraj D_Side_Neutral_Depot = new ChoreoTraj(
	    "D_Side_Neutral_Depot",
	    OptionalInt.empty(),
	    0.69572,
	    new Pose2d(2.956, 5.269, Rotation2d.fromRadians(-1.571)),
	    new Pose2d(3.592, 6.054, Rotation2d.fromRadians(0))
	);

    /**
     * A map between trajectory names and their corresponding data.
     * This allows for trajectory data to be looked up with strings during runtime.
     */
    public static final Map<String, ChoreoTraj> ALL_TRAJECTORIES = Map.ofEntries(
    	Map.entry("Bump_Depot", Bump_Depot),
		Map.entry("Bump_HubLeft", Bump_HubLeft),
		Map.entry("Climb", Climb),
		Map.entry("Depot_Climb", Depot_Climb),
		Map.entry("Depot_HubFront", Depot_HubFront),
		Map.entry("Depot_Outpost", Depot_Outpost),
		Map.entry("HubFront_Outpost", HubFront_Outpost),
		Map.entry("HubLeft_Depot", HubLeft_Depot),
		Map.entry("DepotTrench_Neutral", DepotTrench_Neutral),
		Map.entry("Move_Forward_Depot", Move_Forward_Depot),
		Map.entry("Move_Forward_Outpost", Move_Forward_Outpost),
		Map.entry("Neutral_HubLeft", Neutral_HubLeft),
		Map.entry("OppBump_OppHub", OppBump_OppHub),
		Map.entry("OppNeutral_OppHub", OppNeutral_OppHub),
		Map.entry("Op_Side_Neutral_Outpost", Op_Side_Neutral_Outpost),
		Map.entry("OutpostTrench_NeutralZone", OutpostTrench_NeutralZone),
		Map.entry("Outpost_Tower", Outpost_Tower),
		Map.entry("O_Side_Climb", O_Side_Climb),
		Map.entry("O_Side_Neutral_Climb", O_Side_Neutral_Climb),
		Map.entry("Reverse_From_Hub", Reverse_From_Hub),
		Map.entry("test", test),
		Map.entry("Trench_Outpost", Trench_Outpost),
		Map.entry("NewPath", NewPath),
		Map.entry("D_Side_Neutral_Climb", D_Side_Neutral_Climb),
		Map.entry("D_Side_Neutral_Depot", D_Side_Neutral_Depot)
    );

    /**
     * Looks up the ChoreoTraj segment of the given overall ChoreoTraj.
     * WARNING: will raise an exception if not called with a valid segment index.
     */
    public ChoreoTraj segment(int segment) {
        var traj = ChoreoTraj.ALL_TRAJECTORIES.get(this.name + "$" + segment);
        if (traj == null) {
            throw new NullPointerException("Trajectory " + this.name + " does not have segment #" + segment + ".");
        }
        return traj;
    }
    
    // If these methods cause errors because you're not using ChoreoLib,
    // turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
    /**
     * Load an AutoTrajectory directly from a ChoreoTraj, which may be a segment of a larger trajectory.
     */
    public AutoTrajectory asAutoTraj(AutoRoutine routine) {
        if (this.segment.isPresent()) {
            return routine.trajectory(this.name, this.segment.getAsInt());
        }
        return routine.trajectory(this.name);
    }
}
