/* Generated by Phoenix Tuner X */
package frc.robot.subsystems;

import static edu.wpi.first.units.Units.*;

import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

import com.ctre.phoenix6.CANBus;
import com.ctre.phoenix6.controls.ColorFlowAnimation;
import com.ctre.phoenix6.controls.SolidColor;
import com.ctre.phoenix6.hardware.CANdle;
import com.ctre.phoenix6.signals.AnimationDirectionValue;
import com.ctre.phoenix6.signals.RGBWColor;

/**
 * Subsystem that controls an addressable LED strip using a CANdle.
 */
public class LED extends SubsystemBase {
  private final CANBus kCANBus = new CANBus("");
  private final CANdle m_candle = new CANdle(0, kCANBus);

  private final ColorFlowAnimation m_slot0Animation = new ColorFlowAnimation(0, 255)
      .withSlot(0)
      .withColor(new RGBWColor(45, 255, 1, 0))
      .withDirection(AnimationDirectionValue.Forward)
      .withFrameRate(Hertz.of(2));

  private final SolidColor[] m_colors = new SolidColor[] {
      new SolidColor(0, 255).withColor(new RGBWColor(82, 255, 166, 0)),
      new SolidColor(0, 255).withColor(new RGBWColor(60, 255, 3, 0)),
  };

  public LED() {
    setDefaultCommand(updateLEDs());
  }

  /**
   * Updates the animations and LEDs of the CANdle.
   *
   * @return Command to run
   */
  public Command updateLEDs() {
    return run(() -> {
      for (var solidColor : m_colors) {
        m_candle.setControl(solidColor);
      }
      m_candle.setControl(m_slot0Animation);
    });
  }
}
