/* Generated by Phoenix Tuner X */
package frc.robot.subsystems;

import static edu.wpi.first.units.Units.*;

import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

import com.ctre.phoenix6.CANBus;
import com.ctre.phoenix6.controls.RainbowAnimation;
import com.ctre.phoenix6.controls.SolidColor;
import com.ctre.phoenix6.controls.TwinkleAnimation;
import com.ctre.phoenix6.hardware.CANdle;
import com.ctre.phoenix6.signals.AnimationDirectionValue;
import com.ctre.phoenix6.signals.RGBWColor;

/**
 * Subsystem that controls an addressable LED strip using a CANdle.
 */
public class LED extends SubsystemBase {
  private final CANBus kCANBus = new CANBus("rio");
  private final CANdle m_candle = new CANdle(0, kCANBus);

  private final RainbowAnimation m_slot0Animation = new RainbowAnimation(0, 255)
      .withSlot(0)
      .withBrightness(1)
      .withDirection(AnimationDirectionValue.Forward)
      .withFrameRate(Hertz.of(7.84));

  private final TwinkleAnimation m_slot1Animation = new TwinkleAnimation(0, 255)
      .withSlot(1)
      .withColor(new RGBWColor(255, 255, 255, 0))
      .withMaxLEDsOnProportion(0.5)
      .withFrameRate(Hertz.of(100));

  private final SolidColor[] m_colors = new SolidColor[] {
  };

  public LED() {
    // updateLEDs();
  }

  /**
   * Updates the animations and LEDs of the CANdle.
   *
   * @return Command to run
   */
  public Command updateLEDs() {
    return run(() -> {
      for (var solidColor : m_colors) {
        m_candle.setControl(solidColor);
      }
      m_candle.setControl(m_slot0Animation);
    });
  }

  public Command twinkleLeds() {
    return run(() -> {
      for (var solidColor : m_colors) {
        m_candle.setControl(solidColor);
      }
      m_candle.setControl(m_slot1Animation);
    });
  }

}
